<?xml version="1.0" encoding="utf-8"?><Database Name="tcoder" Class="ChallengeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=115.159.202.201;Initial Catalog=tcoder;Persist Security Info=True;User ID=tang" SettingsObjectName="Model.Properties.Settings" SettingsPropertyName="tcoderConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.challenge" Member="challenge">
    <Type Name="challenge">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="compangId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="language" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="rank" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="sponsor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="salary_range" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="begin_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="end_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="publiced" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="items" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="num" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="del" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>