<?xml version="1.0" encoding="utf-8"?><Database Name="tcoder" ContextNamespace="Recruit" Class="UserChallengeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=115.159.202.201;Initial Catalog=tcoder;Persist Security Info=True;User ID=tang" SettingsObjectName="Model.Properties.Settings" SettingsPropertyName="tcoderConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.user_challenge" Member="user_challenge">
    <Type Name="user_challenge">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="challengeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userState" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="highest" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="completed_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="del" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="isHistory" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>