#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tcoder")]
	public partial class UserChallengeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertuser_challenge(user_challenge instance);
    partial void Updateuser_challenge(user_challenge instance);
    partial void Deleteuser_challenge(user_challenge instance);
    #endregion
		
		public UserChallengeDataContext() : 
				base(global::Model.Properties.Settings.Default.tcoderConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UserChallengeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserChallengeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserChallengeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserChallengeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<user_challenge> user_challenge
		{
			get
			{
				return this.GetTable<user_challenge>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_challenge")]
	public partial class user_challenge : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _userId;
		
		private int _challengeId;
		
		private System.Nullable<short> _userState;
		
		private System.Nullable<int> _highest;
		
		private System.Nullable<System.DateTime> _completed_time;
		
		private short _del;
		
		private System.Nullable<short> _isHistory;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    partial void OnchallengeIdChanging(int value);
    partial void OnchallengeIdChanged();
    partial void OnuserStateChanging(System.Nullable<short> value);
    partial void OnuserStateChanged();
    partial void OnhighestChanging(System.Nullable<int> value);
    partial void OnhighestChanged();
    partial void Oncompleted_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncompleted_timeChanged();
    partial void OndelChanging(short value);
    partial void OndelChanged();
    partial void OnisHistoryChanging(System.Nullable<short> value);
    partial void OnisHistoryChanged();
    #endregion
		
		public user_challenge()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeId", DbType="Int NOT NULL")]
		public int challengeId
		{
			get
			{
				return this._challengeId;
			}
			set
			{
				if ((this._challengeId != value))
				{
					this.OnchallengeIdChanging(value);
					this.SendPropertyChanging();
					this._challengeId = value;
					this.SendPropertyChanged("challengeId");
					this.OnchallengeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userState", DbType="SmallInt")]
		public System.Nullable<short> userState
		{
			get
			{
				return this._userState;
			}
			set
			{
				if ((this._userState != value))
				{
					this.OnuserStateChanging(value);
					this.SendPropertyChanging();
					this._userState = value;
					this.SendPropertyChanged("userState");
					this.OnuserStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_highest", DbType="Int")]
		public System.Nullable<int> highest
		{
			get
			{
				return this._highest;
			}
			set
			{
				if ((this._highest != value))
				{
					this.OnhighestChanging(value);
					this.SendPropertyChanging();
					this._highest = value;
					this.SendPropertyChanged("highest");
					this.OnhighestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_completed_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> completed_time
		{
			get
			{
				return this._completed_time;
			}
			set
			{
				if ((this._completed_time != value))
				{
					this.Oncompleted_timeChanging(value);
					this.SendPropertyChanging();
					this._completed_time = value;
					this.SendPropertyChanged("completed_time");
					this.Oncompleted_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_del", DbType="SmallInt NOT NULL")]
		public short del
		{
			get
			{
				return this._del;
			}
			set
			{
				if ((this._del != value))
				{
					this.OndelChanging(value);
					this.SendPropertyChanging();
					this._del = value;
					this.SendPropertyChanged("del");
					this.OndelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isHistory", DbType="SmallInt")]
		public System.Nullable<short> isHistory
		{
			get
			{
				return this._isHistory;
			}
			set
			{
				if ((this._isHistory != value))
				{
					this.OnisHistoryChanging(value);
					this.SendPropertyChanging();
					this._isHistory = value;
					this.SendPropertyChanged("isHistory");
					this.OnisHistoryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
