<?xml version="1.0" encoding="utf-8"?><Database Name="tcoder" Class="UserDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=115.159.202.201;Initial Catalog=tcoder;Persist Security Info=True;User ID=tang" SettingsObjectName="Model.Properties.Settings" SettingsPropertyName="tcoderConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[user]" Member="user">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="del" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="salt" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
    </Type>
  </Table>
</Database>